### ISSUE TITLE
No source of aluminum

### ISSUE THREAD

**Issue by SoullessWaffle** [BBoldt/ThePioneers#59]
This means crafting e.g. aluminum brass for Tinker's Construct casts is impossible (although you can create casts from other materials).
According to JEI, Foundry does add aluminum, but it's "deprecated".

**Comment by BBoldt** [comment]
Tinkers Construct was the one adding aluminum in previous Minecraft versions. Since they have not readded it themselves, what do you suggest I do?

Just use gold to make casts.

**Comment by SoullessWaffle** [comment]
Yeah, I guess this is one of those `Awaiting Fix` issues. It seems silly to add a new mod just to fix this, when the Tinker's Construct devs can re-add it at any time.

**Comment by BBoldt** [comment]
There isn't going to be a fix.
https://github.com/SlimeKnights/TinkersConstruct/issues/1955

We don't have any mods generating aluminum, therefore we have no way to make aluminum brass. This issue did remind me to turn off the depreciated foundry ingots though, so that's some ids freed up I guess. :P
