### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by PlasmaNoodle** [BBoldt/ThePioneers#67]
Its me... again... it was working fine earlier and i added a few mods for personal enjoyment and now i am crashing (it was working before with the mods) pastebin crash [here](http://pastebin.com/e1qEHJww)

**Comment by BBoldt** [comment]
RTG is erroring for some reason, if you edited anything involving that, undo it. Or just don't use RTG.

Try deleting and regenerating the RTG configs.

**Comment by PlasmaNoodle** [comment]
I found a way around the crash. Of course, its so simple, Pioneers is installing the WRONG version of forge and bugs out with the version and the mods available. Not saying its your fault... but you created it and not looking into the simple stuff first is kind of a let down on the consumers part.

**Comment by BBoldt** [comment]
You must have changed the settings yourself. A fresh install of pioneers will use Forge 1808. 

Simply opening up the settings menu, unclicking the "locked" button, and saving will switch you to Forge 1855 (or whatever is the latest forge). Nothing I can do about that.

![](http://i.imgur.com/02jBoo8.png)

Consumer implies you purchased something, who did you buy this modpack from? :stuck_out_tongue: 
Sorry i'm not giving good enough free support. >.>

**Comment by PlasmaNoodle** [comment]
Uh, i never bought anything? nor did i buy the pack. i downloaded it straight off of the curse launcher. Also, that's not what i am saying, you close the problems before you find a solution and others had the same problem too and i found them all CLOSED.

**Comment by PlasmaNoodle** [comment]
Not trying to be rude or anything, but the fact that you are implying it was my fault because i touched the settings is absurd. I checked there and every time i go to open it, with the locked setting ON, i have to make sure its on the correct version of forge otherwise this crash happens.

**Comment by BBoldt** [comment]
The problem is, you are being rude. You expect me to jump through hoops for you to help you when I've already put more than enough effort into this problem. I know you didn't buy the pack, which is why you should stop acting like you did buy the pack. I do this for free, as a hobby, I don't owe support to you or anyone. I offer support in my free time, as a courtesy to anyone who would like to play my pack.

Since you want to be snippy with me, let's review your problems.

#66 "What's wrong with my launcher"
I still don't know what was causing this issue. You are the first and only person who has reported it to me. Since you didn't even get to the point of loading minecraft, there was not much I could do. Which is why I recommended you to file a bug report with curse, as it has to be a problem with their launcher or with your system setup.

#67 (this issue)
First thing you mentioned was that you had added additional mods to the pack. If you're going to change things in the pack on your own, remove them from the equation before trying to report an issue. 

Despite this, I looked into your crash report and saw that it must have something to do with RTG, as that is the mod erroring. Since the issue can't be reproduced on my end, and because nobody else has experienced that particular issue, I concluded that it must be something you specifically are doing and closed the issue.

Then you come back and tell me what caused the issue, RTG was erroring with the wrong forge version. You then go on to blame that on me, and then say i'm not providing good enough support for the "consumer" for such a simple fix! 

What you have failed to realize even after I told you in the next comment, is the error is a problem with the curse launcher. Even opening the "Profile Options" menu and saving it will change the forge version. Once again, I would suggest you report this to curse, as it is an issue with their launcher, not the modpack! 

You said that there are others experiencing this issue who got their issue closed. WHERE?! 

I'm not implying it's your fault, but opening that menu and saving it is what caused the issue. If you had set the global minecraft memory in the curse launcher settings and not touched that "profile options" menu at all, you would have never had that problem.
