### ISSUE TITLE
Technic pack unable to download file from Google Drive

### ISSUE THREAD

**Issue by bwbaugh** [BBoldt/ThePioneers#78]
#### Issue Description:

When installing [the mod](http://technicpack.net/modpack/the-pioneers.802436) via the Technic Launcher, an error occurs when trying to download a file from Google Drive.

When going to the download link directly: https://drive.google.com/uc?export=download&id=0Bywb6Ud2QMvJdUgwSnlOenVhTzg The error message is:

> Google Drive can't scan this file for viruses.
> Pioneers_Release.1.Beta.technic.zip (133M) exceeds the maximum size that Google can scan. Would you still like to download this file?

I could download directly but couldn't make progress even after manually extracting to the local modpack directory.

#### What happens:

The mod installer errors out and cannot install.

#### What should be happening:

The mod installer should be able to download all files and install correctly.

#### How to reproduce:

Download the Technic Launcher and try to install The Pioneers modpack.

#### Questions:
- Are you on the latest version of the modpack?: n/a
- Have you added any additional mods, and if so, have you tried reproducing the issue without them?: n/a
- Server or client issue?: Client.

**Comment by BBoldt** [comment]
Sorry, I never really meant to support technic launcher. As you can see, I have no reliable place to host the files. The only reason it's there is because I was experimenting and trying to make it work.

Best place to get the pack is here:
http://minecraft.curseforge.com/projects/the-pioneers

I may try to bring the pack to other launchers in the future, but I don't really have the time to do it at the moment and I don't know if I will.
