### ISSUE TITLE
EIO grains of infinity not craftable

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/ThePioneers#95]
Bedrock burns with soul fire.

**Comment by BBoldt** [comment]
Tried to fix this by making it work with deepslate, but it did not work.

I did manage to make bedrock burn with normal fire again using crafttweaker.

There seems to be something with the aether breaking it also.
https://github.com/Team-EnderIO/EnderIO/issues/603

**Comment by BBoldt** [comment]
My plan is to try making a datapack so it works in the nether. I think the aether thing is only breaking it in the overworld.

**Comment by krumble1** [comment]
@Techjar created [a fix for this](https://github.com/Team-EnderIO/EnderIO/issues/603#issuecomment-1932002926) that was merged into EnderIO, but while we wait for the release with that fix, here's a proposed alternate crafting recipe for grains of infinity.

- Change the Primitive Alloy Smelter's crafting recipe to use `minecraft:bricks` (the brick block) in place of the grains of infinity.
- Reason: bricks are also used in the recipe for the _Thermal Series_ redstone furnace which is a somewhat thematically similar item, and bricks are still a little bit of a process to make in the early game.
&nbsp;
- Make a Smelter recipe where 1x iron ingot, 1x coal, and 1x deepslate outputs 4x grains of infinity. This recipe should take 3,200 µI / FE.
- Reason: this recipe closely resembles the pattern for creating darksteel, but is balanced by outputting 4 items and using half the smelting energy requirement (darksteel uses 6,400 µI), since grains of infinity is a less rare ingredient than darksteel; also, coal instead of powdered coal is used since the SAG mill cannot be crafted yet and many players may not know about the mechanic of making powdered coal by holding flint in an off-hand and coal in the main hand while shift + right-clicking an obsidian block.

**Comment by BBoldt** [comment]
Thank you, I will implement this in the next release of the pack!

**Comment by BBoldt** [comment]
I was able to do this pretty easily:
![](https://i.imgur.com/6fIxtq1.png)
![](https://i.imgur.com/xx1z6es.png)
![](https://i.imgur.com/aer6ObO.png)
